version: '3.9'

services:
  expenses-tracker:
    container_name: expenses_tracker
    image: clumped/expenses_tracker
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=jdbc:postgresql://psql-db:5432/postgres
      - DATABASE_USERNAME=clumped
      - DATABASE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
      
  psql-db:
    container_name: psql-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}